# mysql:8
services:
  mysql:
    image: mysql:8
    container_name: e5renew-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-e5renew}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: e5renew-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-e5renew}
      POSTGRES_USER: ${POSTGRES_USER:-e5renew}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-15432}:5432" # expose on 15432 to avoid default collisions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  mysql_data:
  postgres_data:
