apiVersion: v1
kind: Secret
metadata:
  name: {{ include "e5renew.fullname" . }}-secret
  labels:
    {{- include "e5renew.labels" . | nindent 4 }}
type: Opaque
data:
  database-dsn: {{ .Values.config.database.dsn | b64enc }}
  azuread-tenant: {{ .Values.config.azuread.tenant | b64enc }}
  azuread-client-id: {{ .Values.config.azuread.clientId | b64enc }}
  azuread-client-secret: {{ .Values.config.azuread.clientSecret | b64enc }}
  usertoken-tenant: {{ .Values.config.userToken.tenant | b64enc }}
  usertoken-client-id: {{ .Values.config.userToken.clientId | b64enc }}
  usertoken-client-secret: {{ .Values.config.userToken.clientSecret | b64enc }}
  encryption-key: {{ .Values.config.encryptionKey | b64enc }}
