// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysql

import (
	"database/sql"
	"time"
)

type ApiLog struct {
	ID             int64
	UserID         sql.NullString
	ApiEndpoint    string
	HttpMethod     string
	HttpStatusCode int32
	RequestTime    time.Time
	ResponseTime   time.Time
	DurationMs     int32
	RequestSize    sql.NullInt32
	ResponseSize   sql.NullInt32
	ErrorMessage   sql.NullString
	JobType        string
	Success        bool
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type UserToken struct {
	ID           int64
	UserID       string
	AccessToken  string
	RefreshToken string
	Expiry       time.Time
	TokenType    string
}
