// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.postgres.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const createAPILog = `-- name: CreateAPILog :execresult
INSERT INTO api_logs (
    user_id,
    api_endpoint,
    http_method,
    http_status_code,
    request_time,
    response_time,
    duration_ms,
    request_size,
    response_size,
    error_message,
    job_type,
    success
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateAPILogParams struct {
	UserID         sql.NullString
	ApiEndpoint    string
	HttpMethod     string
	HttpStatusCode int32
	RequestTime    time.Time
	ResponseTime   time.Time
	DurationMs     int32
	RequestSize    sql.NullInt32
	ResponseSize   sql.NullInt32
	ErrorMessage   sql.NullString
	JobType        string
	Success        bool
}

func (q *Queries) CreateAPILog(ctx context.Context, arg CreateAPILogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAPILog,
		arg.UserID,
		arg.ApiEndpoint,
		arg.HttpMethod,
		arg.HttpStatusCode,
		arg.RequestTime,
		arg.ResponseTime,
		arg.DurationMs,
		arg.RequestSize,
		arg.ResponseSize,
		arg.ErrorMessage,
		arg.JobType,
		arg.Success,
	)
}

const createUserTokens = `-- name: CreateUserTokens :execresult
insert into user_tokens (
        user_id,
        access_token,
        refresh_token,
        expiry,
        token_type
    )
values ($1, $2, $3, $4, $5)
`

type CreateUserTokensParams struct {
	UserID       string
	AccessToken  string
	RefreshToken string
	Expiry       time.Time
	TokenType    string
}

func (q *Queries) CreateUserTokens(ctx context.Context, arg CreateUserTokensParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserTokens,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expiry,
		arg.TokenType,
	)
}

const deleteOldAPILogs = `-- name: DeleteOldAPILogs :exec
DELETE FROM api_logs
WHERE request_time < $1
`

func (q *Queries) DeleteOldAPILogs(ctx context.Context, requestTime time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldAPILogs, requestTime)
	return err
}

const deleteUserTokens = `-- name: DeleteUserTokens :exec
delete from user_tokens
where user_id = $1
`

func (q *Queries) DeleteUserTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserTokens, userID)
	return err
}

const getAPILogStats = `-- name: GetAPILogStats :one
SELECT
    COUNT(*) as total_requests,
    COUNT(CASE WHEN success = true THEN 1 END) as successful_requests,
    COUNT(CASE WHEN success = false THEN 1 END) as failed_requests,
    AVG(duration_ms) as avg_duration_ms,
    MIN(duration_ms) as min_duration_ms,
    MAX(duration_ms) as max_duration_ms
FROM api_logs
WHERE request_time >= $1 AND request_time <= $2
`

type GetAPILogStatsParams struct {
	RequestTime   time.Time
	RequestTime_2 time.Time
}

type GetAPILogStatsRow struct {
	TotalRequests      int64
	SuccessfulRequests int64
	FailedRequests     int64
	AvgDurationMs      float64
	MinDurationMs      interface{}
	MaxDurationMs      interface{}
}

func (q *Queries) GetAPILogStats(ctx context.Context, arg GetAPILogStatsParams) (GetAPILogStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAPILogStats, arg.RequestTime, arg.RequestTime_2)
	var i GetAPILogStatsRow
	err := row.Scan(
		&i.TotalRequests,
		&i.SuccessfulRequests,
		&i.FailedRequests,
		&i.AvgDurationMs,
		&i.MinDurationMs,
		&i.MaxDurationMs,
	)
	return i, err
}

const getAPILogStatsByEndpoint = `-- name: GetAPILogStatsByEndpoint :many
SELECT
    api_endpoint,
    COUNT(*) as total_requests,
    COUNT(CASE WHEN success = true THEN 1 END) as successful_requests,
    COUNT(CASE WHEN success = false THEN 1 END) as failed_requests,
    AVG(duration_ms) as avg_duration_ms
FROM api_logs
WHERE request_time >= $1 AND request_time <= $2
GROUP BY api_endpoint
ORDER BY total_requests DESC
`

type GetAPILogStatsByEndpointParams struct {
	RequestTime   time.Time
	RequestTime_2 time.Time
}

type GetAPILogStatsByEndpointRow struct {
	ApiEndpoint        string
	TotalRequests      int64
	SuccessfulRequests int64
	FailedRequests     int64
	AvgDurationMs      float64
}

func (q *Queries) GetAPILogStatsByEndpoint(ctx context.Context, arg GetAPILogStatsByEndpointParams) ([]GetAPILogStatsByEndpointRow, error) {
	rows, err := q.db.QueryContext(ctx, getAPILogStatsByEndpoint, arg.RequestTime, arg.RequestTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAPILogStatsByEndpointRow
	for rows.Next() {
		var i GetAPILogStatsByEndpointRow
		if err := rows.Scan(
			&i.ApiEndpoint,
			&i.TotalRequests,
			&i.SuccessfulRequests,
			&i.FailedRequests,
			&i.AvgDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPILogs = `-- name: GetAPILogs :many
SELECT id, user_id, api_endpoint, http_method, http_status_code, request_time, response_time, duration_ms, request_size, response_size, error_message, job_type, success FROM api_logs
ORDER BY request_time DESC
LIMIT $1 OFFSET $2
`

type GetAPILogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAPILogs(ctx context.Context, arg GetAPILogsParams) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, getAPILogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiEndpoint,
			&i.HttpMethod,
			&i.HttpStatusCode,
			&i.RequestTime,
			&i.ResponseTime,
			&i.DurationMs,
			&i.RequestSize,
			&i.ResponseSize,
			&i.ErrorMessage,
			&i.JobType,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPILogsByJobType = `-- name: GetAPILogsByJobType :many
SELECT id, user_id, api_endpoint, http_method, http_status_code, request_time, response_time, duration_ms, request_size, response_size, error_message, job_type, success FROM api_logs
WHERE job_type = $1
ORDER BY request_time DESC
LIMIT $2 OFFSET $3
`

type GetAPILogsByJobTypeParams struct {
	JobType string
	Limit   int32
	Offset  int32
}

func (q *Queries) GetAPILogsByJobType(ctx context.Context, arg GetAPILogsByJobTypeParams) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, getAPILogsByJobType, arg.JobType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiEndpoint,
			&i.HttpMethod,
			&i.HttpStatusCode,
			&i.RequestTime,
			&i.ResponseTime,
			&i.DurationMs,
			&i.RequestSize,
			&i.ResponseSize,
			&i.ErrorMessage,
			&i.JobType,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPILogsByTimeRange = `-- name: GetAPILogsByTimeRange :many
SELECT id, user_id, api_endpoint, http_method, http_status_code, request_time, response_time, duration_ms, request_size, response_size, error_message, job_type, success FROM api_logs
WHERE request_time >= $1 AND request_time <= $2
ORDER BY request_time DESC
LIMIT $3 OFFSET $4
`

type GetAPILogsByTimeRangeParams struct {
	RequestTime   time.Time
	RequestTime_2 time.Time
	Limit         int32
	Offset        int32
}

func (q *Queries) GetAPILogsByTimeRange(ctx context.Context, arg GetAPILogsByTimeRangeParams) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, getAPILogsByTimeRange,
		arg.RequestTime,
		arg.RequestTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiEndpoint,
			&i.HttpMethod,
			&i.HttpStatusCode,
			&i.RequestTime,
			&i.ResponseTime,
			&i.DurationMs,
			&i.RequestSize,
			&i.ResponseSize,
			&i.ErrorMessage,
			&i.JobType,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPILogsByUser = `-- name: GetAPILogsByUser :many
SELECT id, user_id, api_endpoint, http_method, http_status_code, request_time, response_time, duration_ms, request_size, response_size, error_message, job_type, success FROM api_logs
WHERE user_id = $1
ORDER BY request_time DESC
LIMIT $2 OFFSET $3
`

type GetAPILogsByUserParams struct {
	UserID sql.NullString
	Limit  int32
	Offset int32
}

func (q *Queries) GetAPILogsByUser(ctx context.Context, arg GetAPILogsByUserParams) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, getAPILogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiEndpoint,
			&i.HttpMethod,
			&i.HttpStatusCode,
			&i.RequestTime,
			&i.ResponseTime,
			&i.DurationMs,
			&i.RequestSize,
			&i.ResponseSize,
			&i.ErrorMessage,
			&i.JobType,
			&i.Success,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserToken = `-- name: GetUserToken :one
select id, user_id, access_token, refresh_token, expiry, token_type
from user_tokens
where user_id = $1
limit 1
`

func (q *Queries) GetUserToken(ctx context.Context, userID string) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, userID)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.TokenType,
	)
	return i, err
}

const listUserTokens = `-- name: ListUserTokens :many
select id, user_id, access_token, refresh_token, expiry, token_type
from user_tokens
order by user_id
`

func (q *Queries) ListUserTokens(ctx context.Context) ([]UserToken, error) {
	rows, err := q.db.QueryContext(ctx, listUserTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToken
	for rows.Next() {
		var i UserToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Expiry,
			&i.TokenType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTokens = `-- name: UpdateUserTokens :execresult
update user_tokens
set access_token = $1,
    refresh_token = $2,
    expiry = $3,
    token_type = $4
where user_id = $5
`

type UpdateUserTokensParams struct {
	AccessToken  string
	RefreshToken string
	Expiry       time.Time
	TokenType    string
	UserID       string
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserTokens,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expiry,
		arg.TokenType,
		arg.UserID,
	)
}
